package com.example.runforrun.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF399B3D)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFE1FCE2)
val light_onPrimaryContainer = Color(0xFF004103)
val light_secondary = Color(0xFF5A6F5A)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFDDFADE)
val light_onSecondaryContainer = Color(0xFF00796B)
val light_tertiary = Color(0xFF805B72)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFFCD3E9)
val light_onTertiaryContainer = Color(0xFF38152D)
val light_error = Color(0xFFBD1919)
val light_errorContainer = Color(0xFFFCD7D3)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF3C0002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF1D1D22)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF1D1D20)
val light_surfaceVariant = Color(0xFFE0E9E0)
val light_onSurfaceVariant = Color(0xFF4B5755)
val light_outline = Color(0xFF777680)
val light_inverseOnSurface = Color(0xFFE8EEE9)
val light_inverseSurface = Color(0xFF303534)
val light_inversePrimary = Color(0xFFB4F7B7)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF50C556)
val light_outlineVariant = Color(0xFFCED6CE)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFBAFABD)
val dark_onPrimary = Color(0xFF014705)
val dark_primaryContainer = Color(0xFF426B1E)
val dark_onPrimaryContainer = Color(0xFFD8F8D9)
val dark_secondary = Color(0xFFBED6BF)
val dark_onSecondary = Color(0xFF283C29)
val dark_secondaryContainer = Color(0xFF435744)
val dark_onSecondaryContainer = Color(0xFFE2FAE3)
val dark_tertiary = Color(0xFFE6B7D2)
val dark_onTertiary = Color(0xFF442439)
val dark_tertiaryContainer = Color(0xFF58384C)
val dark_onTertiaryContainer = Color(0xFFFAD4E8)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF8B010A)
val dark_onError = Color(0xFF5E0005)
val dark_onErrorContainer = Color(0xFFFAD5D1)
val dark_background = Color(0xFF1B1B1F)
val dark_onBackground = Color(0xFFE5E1E6)
val dark_surface = Color(0xFF1B1B1F)
val dark_onSurface = Color(0xFFE5E1E6)
val dark_surfaceVariant = Color(0xFF42424B)
val dark_onSurfaceVariant = Color(0xFFBDCABE)
val dark_outline = Color(0xFF8E8C97)
val dark_inverseOnSurface = Color(0xFF16161A)
val dark_inverseSurface = Color(0xFFE4E7E4)
val dark_inversePrimary = Color(0xFF42B447)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFBAFABD)
val dark_outlineVariant = Color(0xFF45454E)
val dark_scrim = Color(0xFF000000)

val green = Color(0xFF31A851)